services:
  postgres:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ai_restaurants
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:secret@postgres:5432/ai_restaurants
    depends_on:
      - postgres
  
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend